name: Docker Copy
description:  Run steps using docker
author: tj-actions
inputs:
  container:
    description: 'Container name'
    required: true
  source:
    description: 'Source file or directory'
    required: true
  destination:
    description: 'Destination file or directory'
    required: true
  local:
    description: 'Copy from local to container'
    required: false
    default: 'false'
  options:
    description: 'Additional options'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Docker copy
      shell: bash
      run: |
          if [ "${{ inputs.local }}" = "true" ]; then
            docker cp ${{ inputs.options }} ${{ inputs.source }} ${{ inputs.container }}:${{ inputs.destination }}
          else
            docker cp ${{ inputs.options }} ${{ inputs.container }}:${{ inputs.source }} ${{ inputs.destination }}
          fi

branding:
  icon: refresh-cw
  color: white
