name: Docker Copy
description:  Run steps using docker
author: tj-actions
inputs:
  container:
    description: 'Container name'
    required: true
  source:
    description: 'Source file or directory'
    required: true
  destination:
    description: 'Destination file or directory'
    required: true
  local:
    description: 'Copy from container to local'
    required: false
    default: 'true'
  options:
    description: 'Additional options passed to [docker cp](https://docs.docker.com/engine/reference/commandline/cp/#options)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Docker copy
      shell: bash
      run: |
          # Run docker cp
          EXTRA_ARGS=${{ inputs.options }}

          if [ "${{ inputs.local }}" != "true" ]; then
            docker cp $EXTRA_ARGS ${{ inputs.source }} ${{ inputs.container }}:${{ inputs.destination }}
          else
            docker cp $EXTRA_ARGS ${{ inputs.container }}:${{ inputs.source }} ${{ inputs.destination }}
          fi

branding:
  icon: refresh-cw
  color: white
