name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test docker-cp
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build
        uses: docker/build-push-action@v3
        id: docker-build
        with:
          context: .
          load: true
          push: false
          tags: user/app:latest

      - name: Run
        uses: tj-actions/docker-run@v2
        with:
          image: user/app:latest
          options: --name test-app -d
          args: bash -c 'ls && sleep 1000'

      - name: Copy from container to host
        uses: ./
        with:
          container: test-app
          source: entrypoint.sh
          destination: entrypoint-new.sh

      - name: Display contents of test.txt
        run: cat entrypoint-new.sh
